apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: "true" # Configures the argocd-server to run in insecure mode
  server.basehref: "/argocd" # Sets the base URL for Argo CD when running behind a reverse proxy
