apiVersion: v1
kind: ConfigMap
metadata:
  name: copyparty-config
data:
  copyparty.conf: |
    [global]
    rp-loc: /copyparty/

    [/]     # this URL will be mapped to...
      /w    # ...this folder on the server filesystem
      accs:
        rw: *

---
apiVersion: v1
kind: Service
metadata:
  name: copyparty
spec:
  ports:
    - name: copyparty
      port: 80
      targetPort: 3923
  selector:
    app: copyparty

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty
spec:
  selector:
    matchLabels:
      app: copyparty
  replicas: 1
  template:
    metadata:
      labels:
        app: copyparty
    spec:
      volumes:
        - name: copypartydatadir
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi   # optional limit
        - name: config-volume
          configMap:
            name: copyparty-config
      containers:
        - name: copyparty
          image: ghcr.io/9001/copyparty-ac:1.19.20
          imagePullPolicy: Always
          ports:
            - containerPort: 3923
          env:
          - name: PRTY_CONFIG
            value: "/etc/copyparty/copyparty.conf"
          volumeMounts:
            - name: copypartydatadir
              mountPath: /w
            - name: config-volume
              mountPath: /etc/copyparty
              


