---
apiVersion: v1
kind: Service
metadata:
  name: duckdb
spec:
  ports:
    - name: master
      port: 4213
  selector:
    app: duckdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdb-deployment
spec:
  selector:
    matchLabels:
      app: duckdb
  template:
    metadata:
      labels:
        app: duckdb
    spec:
      nodeSelector:
        disktype: MEM
      containers: 
        - name: duckdb
          image: duckdb/duckdb:1.3.2
          command: ["duckdb"]
          args: ["-cmd", "CALL start_ui_server();"]
          ports:
            - containerPort: 4213