---
apiVersion: v1
kind: Service
metadata:
  name: mediastreamer
spec:
  ports:
    - name: mediastreamerport
      port: 3000
      targetPort: 3000
  selector:
    app: mediastreamer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediastreamer
spec:
  selector:
    matchLabels:
      app: mediastreamer
  replicas: 1
  template:
    metadata:
      labels:
        app: mediastreamer
    spec:
      nodeSelector:
        disktype: MEM
      containers:
        - name: mediastreamer
          image: ghcr.io/mnsrulz/mediastreamer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: LINKS_API_URL
              valueFrom:
                secretKeyRef:
                  name: mediacstreamer
                  key: LINKS_API_URL
            - name: LOGTAIL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mediacatalogworker
                  key: LOGTAIL_TOKEN
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: MAX_BUFFER_SIZE_MB
              value: "1024"
            - name: ROOT_PATH
              value: "/streamer"



