---
apiVersion: v1
kind: Service
metadata:
  name: mzworker-service
spec:
  ports:
    - name: mzworkerport
      port: 8000
      targetPort: 8000
  selector:
    app: mzworker

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mzworker-deployment
spec:
  selector:
    matchLabels:
      app: mzworker
  template:
    metadata:
      labels:
        app: mzworker
    spec:
      volumes:
        - name: rclone-config
          secret:
            secretName: blob-rclone-conf
        - name: rclone-cache
          hostPath:
            path: /tmp/rclone-mzworker-cache
            type: DirectoryOrCreate
      nodeSelector:
        disktype: MEM
      containers: 
        - name: deno
          securityContext:
            privileged: true
          image: ghcr.io/mnsrulz/deno-rclone:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/rcloneconfig/rclone.conf"
              name: rclone-config
              subPath: rclone.conf
            - mountPath: /cache
              name: rclone-cache
          env:
            - name: DATA_DIR
              value: "/data/options_data"
            - name: OHLC_DIR
              value: "/data/ohlc" 
            - name: PUSHER_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: mzworker
                  key: PUSHER_APP_KEY
            - name: PUSHER_URI
              valueFrom:
                secretKeyRef:
                  name: mzworker
                  key: PUSHER_URI
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: mzworker
                  key: REDIS_URI
            - name: VALKEY_URI
              value: "immichredis"       # Kubernetes Service name for Redis
            - name: LOGTAIL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mzworker
                  key: LOGTAIL_TOKEN