---
apiVersion: v1
kind: Service
metadata:
  name: plex-service
spec:
  ports:
    - port: 32400
      targetPort: 32400
  selector:
    app: plex

---
apiVersion: v1
kind: Service
metadata:
 name: jellyfin-service
spec:
 ports:
   - port: 8096
     targetPort: 8096
 selector:
   app: plex


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      volumes:
        - name: mediadownloads # custom download directory
          hostPath:
            path: /home/madhu/Downloads
        - name: plexconfig # plex configuration data like library metadata 
          hostPath:
            path: /home/madhu/plexconfig
        - name: jellyfinconfig # plex configuration data like library metadata 
          hostPath:
            path: /home/madhu/jellyfinconfig
        - name: jellyfincache # plex configuration data like library metadata 
          hostPath:
            path: /home/madhu/jellyfincache
        - name: rcloneconfig # rclone config file directory
          hostPath:
            path: /home/madhu/.config/rclone
        - name: plexmedia
          emptyDir: {}
      containers:
        - name: rclone
          securityContext:
            privileged: true
          image: rclone/rclone
          command:
            - "rclone"
            - "mount"
            - "-v"
            - "--allow-non-empty"
            - "--allow-other"
            - "--read-only"
            - "--vfs-read-chunk-size=1M"
            - "--vfs-read-chunk-size-limit=8M"
            - "AllDrives:/"
            - "/mnt/data"
          volumeMounts:
            - mountPath: /config/rclone
              name: rcloneconfig
            - mountPath: /mnt/data
              name: plexmedia
              mountPropagation: Bidirectional # this is important to make rclone mount visible in other containers (plex)
        - name: plex
          image: linuxserver/plex
#          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /config
              name: plexconfig
            - mountPath: /mediadownloads
              name: mediadownloads
            - mountPath: /media
              name: plexmedia
              readOnly: true
              mountPropagation: HostToContainer
          ports:
            - containerPort: 32400
          env:
            - name: claimToken
              value: "claim-bA9mxYGuAusGiAtccSSR"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: VERSION
              value: "docker"
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
        #  imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /config
              name: jellyfinconfig
            - mountPath: /cache
              name: jellyfincache
            - mountPath: /media
              name: plexmedia
              readOnly: true
              mountPropagation: HostToContainer
          ports:
            - containerPort: 8096
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: "192.168.0.30/jellyfin/"
            - name: PUID
              value: "1000"
            - name: PGID 
              value: "1000"
          resources: # limit the resources
            limits:
              memory: 256Mi
              cpu: 100m
